# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.generic_response_payload import GenericResponsePayload  # noqa: E501
from swagger_client.rest import ApiException


class TestGenericResponsePayload(unittest.TestCase):
    """GenericResponsePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericResponsePayload(self):
        """Test GenericResponsePayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.generic_response_payload.GenericResponsePayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
