# coding: utf-8

"""
    Eclipse Kapua REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_configurations_api import ServiceConfigurationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceConfigurationsApi(unittest.TestCase):
    """ServiceConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.service_configurations_api.ServiceConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_configuration_component_get(self):
        """Test case for service_configuration_component_get

        Gets the configuration of a service on an account  # noqa: E501
        """
        pass

    def test_service_configuration_component_update(self):
        """Test case for service_configuration_component_update

        Updates the configuration of a service on an account  # noqa: E501
        """
        pass

    def test_service_configuration_get(self):
        """Test case for service_configuration_get

        Gets multiple services configurations  # noqa: E501
        """
        pass

    def test_service_configuration_update(self):
        """Test case for service_configuration_update

        Updates multiple services configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
